name: github-actions/build
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          cache: true

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - uses: EndBug/add-and-commit@v9
        with:
          message: '[ci] update go packages'
          add: 'go.*'
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
